matches:
  - trigger: "`1"
    replace: |-
      translate into Chinese

  - trigger: "`2"
    replace: |-
      我觉得本教程语言能力不好,请你用你的风格重新描述,要和原教程完全等价(特别是示例方面),因为我会按照教程目录走(如果有作业请不要解出来让我自己去尝试)

  - trigger: "`3"
    replace: |-
      文中术语进行标准解释后举个简单的帮助我理解的现实生活中的例子(请简短一点每个标准解释和简单的例子分别不超过一句话,并且你只用解释你认为需要解释的术语)

  - trigger: "`4"
    replace: |-
      为什么要取这个名字(我的理解能力不是很好),请给我分别讲取这几个字的中文名字由来的(注意不要讨论古代文字的例如甲骨文,也不要讨论偏旁和部首等我不是语言学家,我只是为了创建联系方便理解这个名字也方便记忆这个名字)(顺便列举它的近义词和反义词和对立词分别有哪些?)(理解这个词的常见误区有哪些?顺便使用这个词进行简单的造句)最后在对于它进行最正式的官方/学术标准解释.

  - trigger: "`5"
    replace: |-
      我没有理解到,请帮我浓缩成极致简短的精华摘要.

  - trigger: "`6"
    replace: |-
      怎么做这道题目这是我写的第一道算法题,只告诉我思考方式和尝试的思维链不要解出来了

  - trigger: "`7"
    replace: |-
      1.不要那么多废话,几句话讲清楚.
      2.不要只给我部分代码
      3.如果你删除了我源文件里面你觉得没有用的代码或者文字或者注释,一定要通知我
      4.这是最新的官方文档,我安装的xxx软件也是从最新的release安装的如果你觉得我的太旧了,那么其实真正的原因是你的知识库太旧了,一切以官方文档为准
      5.我的环境是fedora+sway+fish+neovim+zellij

  - trigger: "`8"
    replace: |-
      我的核心部署文件只有setup.sh,其他都是扯犊子不要单独裸露出来,我只想运行一下setup.sh就能看到效果,要修改代码或者新增文件请你直接给我完整的代码不要指点我去修改

  - trigger: "`9"
    replace: |-
      暂无

  - trigger: "`0"
    replace: |-
      为一本关于<<minecraft redstone深入浅出>>的书设计一个详细的章节大纲。------[粘贴前面生成的目录].这是LLM给我的学习目录,我已经学完前面的章节了,现在请教我第xxx章：你好，红石！—— 红石系统导论 1.1 什么是红石信号？—— 能量的开与关. ------[组织并粘贴整本书]请你帮我判断我的书哪些地方写的不好,请你指出来我去优化.
      我想实现一个围绕spring boot的完整项目,我将完成它作为我的面试实习项目(我希望不是烂大街的项目),!!!!重点一定要放在中国小公司java程序员最常见最真实的工作部分,我的学历是民办本科不太可能去中大厂!!!!,请先分成多个阶段,然后每个阶段分成多个的小任务,任务一定要划小不能再小的那种(我需要你之后一步一步带我做,但是现在先不做忙实现先划分一个具体的清单,我们采用一个最推荐最主流的开发策略,开发模式绝对不能采用瀑布开发,开发周期非常短,只有2个月,并且我还要并行刷Grind75(一个精选的LeetCode题集))和准备八股文. -------------------------我已经完成了这个项目我能不能添加AI功能
      你好我叫傻子,给傻子的spring boot教程,不讲原理直接开始做(我就用类似记事本的东西,OS有可能是fedora,我也太确定是什么OS)
